import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, BellRing, CalendarDays, Camera, Check, ChevronRight, CirclePause, Expand, Home, MessageCircle, MoreHorizontal, Phone, Play, RotateCcw, Settings, ShieldCheck, UserRound, UsersRound, Video, Volume2, VolumeX, Wifi, X } from "lucide-react";
import { alertRecipients, emergencyContact } from "./cameraDetail.mock";
import { fetchCameraDetail } from "./cameraDetail.service";
import type { CameraDetail, CameraEvent, CameraEventType, HistoryFilter } from "./cameraDetail.types";
import { formatAlertDateTime } from "../alerts/alertDateTime";
import { updateAlertStatus } from "../alerts/alertService";
import { CameraStream } from "../../components";
import "./cameraDetail.css";

const eventIcons: Record<CameraEventType, typeof Camera> = { fall_detection:AlertTriangle, immobility:CirclePause, person_detected:UserRound, unknown_person:UsersRound, member_recognized:ShieldCheck, camera_offline:Wifi, camera_online:Wifi, motion_detected:Video, monitoring_paused:CirclePause, monitoring_resumed:Play };
type Dialog = "emergency"|"message"|"recipients"|"pause"|null;

export default function CameraDetailPage({ cameraId }: { cameraId: string }) {
  const sourceParams=new URLSearchParams(window.location.search); const sourceAlertId=sourceParams.get("alert"); const sourceEventId=sourceParams.get("event"); const sourceTime=sourceParams.get("at");
  const [activeCamera,setActiveCamera]=useState<CameraDetail|null>(null); const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState(false); const [muted,setMuted]=useState(true); const [fullscreen,setFullscreen]=useState(false); const [dialog,setDialog]=useState<Dialog>(null); const [selectedEvent,setSelectedEvent]=useState<CameraEvent|null>(null); const [filter,setFilter]=useState<HistoryFilter>("today"); const [pausedUntil,setPausedUntil]=useState(""); const [events,setEvents]=useState<CameraEvent[]>([]); const [videoError,setVideoError]=useState(false);
  const [highlightedEventId,setHighlightedEventId]=useState<string|null>(null); const [linkNotice,setLinkNotice]=useState<string|null>(null);
  useEffect(()=>{setLoading(true);setLoadError(false);fetchCameraDetail(cameraId).then(({camera,events})=>{setActiveCamera(camera);setEvents(events);setSelectedEvent(null);setVideoError(false)}).catch(()=>setLoadError(true)).finally(()=>setLoading(false))},[cameraId]);
  useEffect(()=>{if(loading||!sourceEventId)return;const linkedEvent=events.find(event=>event.id===sourceEventId||event.eventId===sourceEventId);if(!linkedEvent){setLinkNotice("Không tìm thấy sự kiện, đang hiển thị camera hiện tại.");return}setFilter("today");setHighlightedEventId(linkedEvent.id);const scrollTimer=window.setTimeout(()=>document.getElementById(`camera-event-${linkedEvent.id}`)?.scrollIntoView({behavior:"smooth",block:"center"}),120);const clearTimer=window.setTimeout(()=>setHighlightedEventId(null),3000);return()=>{window.clearTimeout(scrollTimer);window.clearTimeout(clearTimer)}},[loading,sourceEventId,events]);
  const visibleEvents=useMemo(()=>filter==="today"?events.filter(event=>event.dayGroup==="Hôm nay"):filter==="custom"?events.filter(event=>event.dayGroup==="28 tháng 7"):events,[events,filter]);
  const groups=useMemo(()=>["Hôm nay","Hôm qua","28 tháng 7"].map(day=>({day,items:visibleEvents.filter(event=>event.dayGroup===day)})).filter(group=>group.items.length),[visibleEvents]);
  const pendingEvent=useMemo(()=>events.find(event=>event.status==="new"||event.status==="need_help"),[events]);
  const navigate=(path:string)=>{window.history.pushState({},"",path);window.dispatchEvent(new PopStateEvent("popstate"))};
  const updateEvent=(status:CameraEvent["status"])=>{if(!selectedEvent)return;const previous=selectedEvent.status;setEvents(items=>items.map(item=>item.id===selectedEvent.id?{...item,status}:item));setSelectedEvent(current=>current?{...current,status}:current);if(selectedEvent.type==="fall_detection"||selectedEvent.type==="unknown_person"){const apiStatus=status==="need_help"?"need_help":status==="false_alarm"?"false_alarm":status==="safe"?"safe":"resolved";void updateAlertStatus(selectedEvent.id,apiStatus).catch(()=>{setEvents(items=>items.map(item=>item.id===selectedEvent.id?{...item,status:previous}:item));setSelectedEvent(current=>current?{...current,status:previous}:current)})}};
  if(loading)return <div className="camera-detail-page camera-detail-loading"><i/><i/><i/><i/></div>;
  if(loadError||!activeCamera)return <div className="camera-detail-page camera-detail-loading"><strong>Không tải được dữ liệu camera từ backend.</strong></div>;
  return <div className="camera-detail-page">
    <CameraDetailHeader camera={activeCamera} onBack={()=>navigate("/camera")} />
    {sourceAlertId&&<AlertSourceBanner alertId={sourceAlertId} event={events.find(event=>event.id===sourceEventId)} occurredAt={sourceTime} onOpenAlert={()=>navigate(`/alerts/${encodeURIComponent(sourceAlertId)}`)} />}
    {linkNotice&&<div className="camera-link-toast" role="status">{linkNotice}<button onClick={()=>setLinkNotice(null)}><X/></button></div>}
    <main className="camera-detail-content">
      <div className="camera-detail-primary">
        <CameraLivePreview camera={activeCamera} muted={muted} error={videoError} onError={()=>setVideoError(true)} onRetry={()=>setVideoError(false)} onMute={()=>setMuted(value=>!value)} onFullscreen={()=>setFullscreen(true)} />
        <SafetyStatusCard pausedUntil={pausedUntil} attention={Boolean(pendingEvent)} />
      </div>
      <div className={`camera-detail-secondary ${pendingEvent?"":"actions-only"}`}>
        {pendingEvent&&<LatestCameraEventCard camera={activeCamera} event={pendingEvent} onOpen={()=>setSelectedEvent(pendingEvent)} />}
        <CameraQuickActions onAction={setDialog} paused={Boolean(pausedUntil)} />
      </div>
      <CameraEventHistory groups={groups} filter={filter} highlightedEventId={highlightedEventId} sourceEventId={sourceEventId} onFilter={setFilter} onOpen={setSelectedEvent} />
    </main>
    {fullscreen&&<CameraFullscreenModal camera={activeCamera} muted={muted} onMute={()=>setMuted(value=>!value)} onClose={()=>setFullscreen(false)} />}
    {selectedEvent&&<CameraEventDetailSheet camera={activeCamera} event={selectedEvent} onClose={()=>setSelectedEvent(null)} onStatus={updateEvent} onCamera={()=>setSelectedEvent(null)} />}
    {dialog&&<ActionDialog type={dialog} pausedUntil={pausedUntil} onPause={setPausedUntil} onClose={()=>setDialog(null)} />}
  </div>;
}

function CameraDetailHeader({camera,onBack}:{camera:CameraDetail;onBack:()=>void}){return <header className="camera-detail-header"><button onClick={onBack} aria-label="Quay lại"><ArrowLeft/></button><div><strong>{camera.name}</strong><span><i/> {camera.status==="online"?"Trực tuyến":"Ngoại tuyến"}</span></div><button aria-label="Cài đặt"><Settings/></button><button aria-label="Tùy chọn"><MoreHorizontal/></button></header>}

function AlertSourceBanner({alertId,event,occurredAt,onOpenAlert}:{alertId:string;event?:CameraEvent;occurredAt:string|null;onOpenAlert:()=>void}){const dateTime=occurredAt?formatAlertDateTime(occurredAt):event?.occurredAt||"";return <aside className="camera-alert-source"><span><AlertTriangle/></span><div><small>Bạn đang xem camera liên quan đến cảnh báo</small><strong>{event?.title||"Sự kiện từ cảnh báo"}{dateTime&&` · ${dateTime}`}</strong></div><button onClick={onOpenAlert}>Xem chi tiết cảnh báo <ChevronRight/></button></aside>}

function CameraLivePreview({camera,muted,error,onError,onRetry,onMute,onFullscreen}:{camera:CameraDetail;muted:boolean;error:boolean;onError:()=>void;onRetry:()=>void;onMute:()=>void;onFullscreen:()=>void}){const [clock,setClock]=useState(new Date());useEffect(()=>{const timer=window.setInterval(()=>setClock(new Date()),1000);return()=>window.clearInterval(timer)},[]);return <section className="detail-live-card">{error?<div className="detail-video-error"><Video/><strong>Chưa thể tải camera</strong><button onClick={onRetry}><RotateCcw/> Thử lại</button></div>:<CameraStream cameraId={camera.id} streamReady={camera.streamReady} streamUrl={camera.streamUrl} playbackUrl={camera.videoUrl} onError={onError}/>}<div className="live-overlay top"><span className={`detail-live-badge ${camera.status==="offline"?"offline":""}`}><i/><span>{camera.status==="offline"?"Ngoại tuyến":"Trực tiếp"}</span></span><button onClick={onMute}>{muted?<VolumeX/>:<Volume2/>}</button><button className="live-fullscreen" onClick={onFullscreen}><Expand/></button></div><div className="live-overlay bottom"><span>{camera.quality}</span><time>{clock.toLocaleTimeString("vi-VN",{hour12:false})}</time></div></section>}

function SafetyStatusCard({pausedUntil,attention}:{pausedUntil:string;attention:boolean}){return <article className={`camera-safety-card ${pausedUntil?"paused":""}`}><span>{attention?<AlertTriangle/>:<ShieldCheck/>}</span><div><h2>{pausedUntil?"Giám sát đang tạm dừng":attention?"Có sự kiện cần kiểm tra":"Khu vực đang an toàn"}</h2><p>{pausedUntil?`Hệ thống sẽ tự tiếp tục sau ${pausedUntil}.`:attention?"Một sự kiện mô phỏng đang chờ bạn xử lý.":"Hiện chưa phát hiện tình huống cần xử lý."}</p><small>Cập nhật theo dữ liệu camera</small></div><Home/></article>}

function LatestCameraEventCard({camera,event,onOpen}:{camera:CameraDetail;event:CameraEvent;onOpen:()=>void}){return <article className="latest-camera-event"><span className="latest-event-icon"><AlertTriangle/></span><div><p>Sự kiện gần nhất</p><h2>{event.title}</h2><span>{event.occurredAt} · {camera.room} · {event.confidence}% tin cậy</span></div><b>Mức cao</b><button onClick={onOpen}>Xem chi tiết <ChevronRight/></button></article>}

function CameraQuickActions({onAction,paused}:{onAction:(dialog:Dialog)=>void;paused:boolean}){const actions=[{id:"emergency" as Dialog,label:"Gọi khẩn cấp",icon:Phone,tone:"danger"},{id:"message" as Dialog,label:"Nhắn tin",icon:MessageCircle},{id:"recipients" as Dialog,label:"Người nhận cảnh báo",icon:UsersRound},{id:"pause" as Dialog,label:paused?"Đổi thời gian dừng":"Tạm dừng giám sát",icon:CirclePause}];return <section className="camera-quick-actions">{actions.map(({id,label,icon:Icon,tone})=><button className={tone||""} key={id} onClick={()=>onAction(id)}><Icon/><span>{label}</span></button>)}</section>}

function CameraEventHistory({groups,filter,highlightedEventId,sourceEventId,onFilter,onOpen}:{groups:{day:string;items:CameraEvent[]}[];filter:HistoryFilter;highlightedEventId:string|null;sourceEventId:string|null;onFilter:(filter:HistoryFilter)=>void;onOpen:(event:CameraEvent)=>void}){return <section className="camera-history"><header><div><h2>Lịch sử sự kiện</h2><p>Những điều camera đã ghi nhận.</p></div><CalendarDays/></header><div className="camera-history-filters">{([{id:"today",label:"Hôm nay"},{id:"7days",label:"7 ngày"},{id:"30days",label:"30 ngày"},{id:"custom",label:"Chọn ngày"}] as {id:HistoryFilter;label:string}[]).map(item=><button className={filter===item.id?"active":""} onClick={()=>onFilter(item.id)} key={item.id}>{item.label}</button>)}</div>{groups.length?groups.map(group=><CameraEventGroup key={group.day} day={group.day} events={group.items} highlightedEventId={highlightedEventId} sourceEventId={sourceEventId} onOpen={onOpen}/>):<div className="camera-history-empty"><CalendarDays/><strong>Không có sự kiện</strong><span>Hãy chọn khoảng thời gian khác.</span></div>}</section>}

function CameraEventGroup({day,events,highlightedEventId,sourceEventId,onOpen}:{day:string;events:CameraEvent[];highlightedEventId:string|null;sourceEventId:string|null;onOpen:(event:CameraEvent)=>void}){return <div className="camera-event-group"><h3>{day} · {events.length} sự kiện</h3>{events.map(event=><CameraEventItem key={event.id} event={event} highlighted={highlightedEventId===event.id} fromAlert={sourceEventId===event.id} onOpen={()=>onOpen(event)}/>)}</div>}

function CameraEventItem({event,highlighted,fromAlert,onOpen}:{event:CameraEvent;highlighted:boolean;fromAlert:boolean;onOpen:()=>void}){const Icon=eventIcons[event.type];return <button id={`camera-event-${event.id}`} className={`camera-event-item severity-${event.severity} ${highlighted?"alert-highlight":""}`} onClick={onOpen}><span className="event-type-icon"><Icon/></span><div><strong>{event.title}</strong><p>{event.description}</p></div>{fromAlert?<b className="from-alert-badge">Từ cảnh báo</b>:event.severity==="high"&&<b>Mức cao</b>}<time>{event.occurredAt}</time><ChevronRight/></button>}

function CameraFullscreenModal({camera,muted,onMute,onClose}:{camera:CameraDetail;muted:boolean;onMute:()=>void;onClose:()=>void}){return <div className="camera-fullscreen-modal"><CameraStream cameraId={camera.id} streamReady={camera.streamReady} streamUrl={camera.streamUrl} playbackUrl={camera.videoUrl}/><header><div><strong>{camera.name}</strong><span><i/> Trực tuyến</span></div><button onClick={onMute}>{muted?<VolumeX/>:<Volume2/>}</button><button onClick={onClose}><X/></button></header></div>}

function CameraEventDetailSheet({camera,event,onClose,onStatus,onCamera}:{camera:CameraDetail;event:CameraEvent;onClose:()=>void;onStatus:(status:CameraEvent["status"])=>void;onCamera:()=>void}){return <div className="camera-sheet-backdrop" onClick={onClose}><section className="camera-event-sheet" onClick={e=>e.stopPropagation()}><header><div><small>Chi tiết sự kiện</small><h2>{event.title}</h2></div><button onClick={onClose}><X/></button></header><div className="event-sheet-snapshot"><span className="scene-window"/><span className="scene-furniture"/><b>{event.occurredAt}</b></div><div className="event-sheet-meta"><span>Camera<strong>{camera.name}</strong></span><span>Vị trí<strong>{camera.room}</strong></span><span>Độ tin cậy<strong>{event.confidence?`${event.confidence}%`:"—"}</strong></span><span>Trạng thái<strong>{event.status==="safe"?"An toàn":"Đang xem xét"}</strong></span></div><p>{event.description}</p><label>Ghi chú<textarea placeholder="Thêm ghi chú cho sự kiện..." defaultValue={event.notes}/></label><div className="event-sheet-actions"><button onClick={onCamera}><Camera/> Mở camera</button><button className="safe" onClick={()=>onStatus("safe")}><Check/> Đánh dấu an toàn</button><button className="danger" onClick={()=>onStatus("need_help")}><BellRing/> Cần hỗ trợ</button><button onClick={()=>onStatus("false_alarm")}>Cảnh báo sai</button></div></section></div>}

function ActionDialog({type,pausedUntil,onPause,onClose}:{type:Exclude<Dialog,null>;pausedUntil:string;onPause:(value:string)=>void;onClose:()=>void}){const [message,setMessage]=useState("");const [duration,setDuration]=useState(pausedUntil||"15 phút");const title={emergency:"Gọi khẩn cấp",message:"Nhắn tin người chăm sóc",recipients:"Người nhận cảnh báo",pause:"Tạm dừng giám sát"}[type];return <div className="camera-dialog-backdrop" onClick={onClose}><section className="camera-action-dialog" onClick={e=>e.stopPropagation()}><header><h2>{title}</h2><button onClick={onClose}><X/></button></header>{type==="emergency"&&<><p>Bạn sắp thực hiện cuộc gọi mô phỏng tới liên hệ chính.</p><div className="contact-row"><span><Phone/></span><div><strong>{emergencyContact.name}</strong><small>{emergencyContact.maskedPhone}</small></div></div><button className="dialog-primary danger" onClick={onClose}>Mô phỏng cuộc gọi</button></>}{type==="message"&&<><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Nhập nội dung cần gửi..."/><button className="dialog-primary" disabled={!message.trim()} onClick={onClose}>Gửi tin nhắn giả</button></>}{type==="recipients"&&<div className="recipient-list">{alertRecipients.map(person=><div key={person.id}><span>{person.name.slice(0,1)}</span><div><strong>{person.name}</strong><small>{person.role}</small></div><i className={person.enabled?"enabled":""}/></div>)}</div>}{type==="pause"&&<><p>Chọn thời gian tạm dừng. Hệ thống sẽ tự tiếp tục sau đó.</p><div className="pause-options">{["15 phút","30 phút","1 giờ"].map(value=><button className={duration===value?"active":""} onClick={()=>setDuration(value)} key={value}>{value}</button>)}</div><button className="dialog-primary" onClick={()=>{onPause(duration);onClose()}}>{pausedUntil?"Cập nhật":"Tạm dừng giám sát"}</button></>}</section></div>}
