num_worker: 8
work_dir: ./work_dir/fall_detection/ntu25-bone/

# feeder
feeder: feeders.feeder_ntu.Feeder

train_feeder_args:
  data_path: ./data/fused_features/train_joint_only
  label_path: ./data/fused_features/train_joint_only/train_label.csv
  debug: False
  random_choose: True
  random_shift: True
  random_move: False
  window_size: 64
  normalization: True
  random_rot: True
  p_interval: [1]
  bone: True

val_feeder_args:
  data_path: ./data/fused_features/val_joint_only
  label_path: ./data/fused_features/val_joint_only/val_label.csv
  split: val
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: True
  random_rot: False
  p_interval: [1]
  bone: True

test_feeder_args:
  data_path: ./data/fused_features/val_joint_only
  label_path: ./data/fused_features/val_joint_only/val_label.csv
  split: test
  window_size: 64
  p_interval: [1]
  bone: True
  debug: False

# model
model: model.SDAGCN.Model
model_args:
  num_class: 2
  num_point: 25
  num_person: 1
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    labeling_mode: 'spatial'
    CoM: 0
  in_channels: 3
  adaptive: True
  drop_out: 0.5

# optim
weight_decay: 0.0004
base_lr: 0.1
warm_up_epoch: 3

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 15
step: [10, 13]
nesterov: True