# command line: main1.py --config config/vsl.yaml --device 0

base_lr: 0.05
batch_size: 64
config: config/vsl.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder_ntu.Feeder
ignore_weights: []
log_interval: 100
loss_type: CE
lr_decay_rate: 0.1
lr_ratio: 0.001
model: model.SDAGCN.Model
model_args:
  adaptive: true
  drop_out: 0.5
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    CoM: 0
    labeling_mode: spatial
  in_channels: 3
  num_class: 5
  num_person: 1
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 30
num_worker: 8
optimizer: SGD
phase: train
print_log: true
save_epoch: 30
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 15
- 20
test_batch_size: 64
test_feeder_args:
  bone: false
  data_path: ./data/fused_features/val_joint_only
  debug: false
  label_path: ./data/fused_features/val_joint_only/val_label.csv
  p_interval:
  - 1
  split: test
  window_size: 64
train_feeder_args:
  bone: false
  data_path: ./data/fused_features/train_joint_only
  debug: false
  label_path: ./data/fused_features/train_joint_only/train_label.csv
  normalization: true
  p_interval:
  - 1
  random_choose: true
  random_move: true
  random_rot: true
  random_shift: true
  window_size: 64
val_feeder_args:
  bone: false
  data_path: ./data/fused_features/val_joint_only
  debug: false
  label_path: ./data/fused_features/val_joint_only/val_label.csv
  normalization: true
  p_interval:
  - 1
  random_choose: false
  random_move: false
  random_rot: false
  random_shift: false
  split: val
  window_size: 64
warm_up_epoch: 3
weight_decay: 0.0004
weights: null
work_dir: ./work_dir/fall_detection/joint
