python main.py --config ./config/vsl.yaml --device 0
python main.py --config ./config/vslbone.yaml --device 0
python main.py --config ./config/vsls28/vslbone.yaml --device 0
python main1.py --config ./config/vsl400left/vslbone.yaml --device 0
python main1.py --config ./config/vsl400center/vsl.yaml --phase test --work-dir ./work_dir/vsl400center/vsl-k8
python main.py --config ./config/vsls28/vslbone.yaml --phase test --weights ./work_dir/vsl_hdsgcn28/vslbone/runs-best_val.pt
python ensemble2.py --joint-score ./work_dir/vsl400/vsl-k8/epoch90_test_score.pkl --bone-score ./work_dir/vsl400/vslbone-k8/epoch69_test_score.pkl --label-csv ./data/VSL400/test.csv --alpha 1.1 --beta 1.0
python ensemble4.py --s1 ./work_dir/vsl400/vsl-k8/epoch90_test_score.pkl --s2 ./work_dir/vsl400/vslbone-k8/epoch69_test_score.pkl --s3 ./work_dir/vsl_hdsgcn28left/vsl/epoch70_test_score.pkl --s4 ./work_dir/vsl_hdsgcn28left/vslbone/epoch78_test_score.pkl --label-csv ./data/hdcgcn/test/test_label.csv --w1 1.1 --w2 2.0 --w3 1.0 --w4 2.0
python ensemble6.py --s1 ./work_dir/vsl_sdagcn28right/vsl/epoch82_test_score.pkl --s2 ./work_dir/vsl_sdagcn28right/vslbone/epoch81_test_score.pkl --s3 ./work_dir/vsl_sdagcn28left/vsl/epoch82_test_score.pkl --s4 ./work_dir/vsl_sdagcn28left/vslbone/epoch84_test_score.pkl --s5 ./work_dir/vsl_sdagcn28/vsl/epoch1_test_score.pkl --s6 ./work_dir/vsl_sdagcn28/vslbone/epoch1_test_score.pkl --label-csv ./data/hdcgcn/test/test_label.csv
python ensemble4.py --s1 ./work_dir/vsl_sdagcn28right/vsl-k8/epoch88_test_score.pkl --s2 ./work_dir/vsl_sdagcn28right/vslbone/epoch81_test_score.pkl --s3 ./work_dir/vsl_sdagcn28left/vsl-k8/epoch84_test_score.pkl --s4 ./work_dir/vsl_sdagcn28left/vslbone/epoch84_test_score.pkl --label-csv ./data/hdcgcn/test/test_label.csv --w1 1.3 --w2 1.5 --w3 1.0 --w4 1.5
python ensemble6.py --config1 ./work_dir/vsl400right/vsl-k8/config.yaml --weight1 ./work_dir/vsl400right/vsl-k8/runs-best_val.pt --config2 ./work_dir/vsl400right/vslbone-k8/config.yaml --weight2 ./work_dir/vsl400right/vslbone-k8/runs-best_val.pt --config3 ./work_dir/vsl400center/vsl-k8/config.yaml --weight3 ./work_dir/vsl400center/vsl-k8/runs-best_val.pt --config4 ./work_dir/vsl400center/vslbone-k8/config.yaml --weight4 ./work_dir/vsl400center/vslbone-k8/runs-best_val.pt --config5 ./work_dir/vsl400left/vsl-k8/config.yaml --weight5 ./work_dir/vsl400left/vsl-k8/runs-best_val.pt --config6 ./work_dir/vsl400left/vslbone-k8/config.yaml --weight6 ./work_dir/vsl400left/vslbone-k8/runs-best_val.pt --lookup_csv ./data/data/MultiVSL200/lookuptable.csv --tta_times 5 --grid_steps 20
python ensemble6.py --config1 ./work_dir/vsl_sdagcn28right/vsl-k7/config.yaml --weight1 ./work_dir/vsl_sdagcn28right/vsl-k7/runs-best_val.pt --config2 ./work_dir/vsl_sdagcn28right/vslbone/config.yaml --weight2 ./work_dir/vsl_sdagcn28right/vslbone/runs-best_val.pt --config3 ./work_dir/vsl_sdagcn28left/vsl-k8new/config.yaml --weight3 ./work_dir/vsl_sdagcn28left/vsl-k8new/runs-best_val.pt --config4 ./work_dir/vsl_sdagcn28left/vslbone-k8new/config.yaml --weight4 ./work_dir/vsl_sdagcn28left/vslbone-k8new/runs-best_val.pt --config5 ./work_dir/vsl_sdagcn28/vsl-k8/config.yaml --weight5 ./work_dir/vsl_sdagcn28/vsl-k8/runs-best_val.pt --config6 ./work_dir/vsl_sdagcn28/vslbone/config.yaml --weight6 ./work_dir/vsl_sdagcn28/vslbone/runs-best_val.pt --lookup_csv ./data/data/MultiVSL200/lookuptable.csv --tta_times 5 --grid_steps 20
demo
python demo/pipeline.py --video demo/videodemo/demo.mp4 --out_npy demo/keypoint/demo_keypoints.npy
python fusion/process_demo.py --input demo/keypoint/demo_keypoints.npy --output demo/keypointfinal/keypointfinal.npy
python infer_npy.py --config ./work_dir/vsl400right/vsl-k8/config.yaml --weights ./work_dir/vsl400right/vsl-k8/runs-best_val.pt --label-map ./data/VSL400/lookuptable400.csv --npy ./demo/keypointfinal/keypointfinal.npy