import {Eye,EyeOff,HeartHandshake,LockKeyhole,ShieldCheck,UserRound} from "lucide-react";
import {useState,type FormEvent} from "react";
import {changePassword,login,type AuthUser} from "../api/auth";
import "./login.css";
export default function LoginPage({onAuthenticated,user}:{onAuthenticated:(user:AuthUser)=>void;user?:AuthUser|null}){
 const [visible,setVisible]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget);try{if(user?.force_password_change){onAuthenticated(await changePassword(String(form.get("password"))))}else{onAuthenticated(await login(String(form.get("identity")),String(form.get("password")),form.get("remember")==="on"))}}catch(err){setError(err instanceof Error?err.message:"Không thể đăng nhập") }finally{setLoading(false)}};
 return <main className="login-page"><section className="login-brand-panel"><div className="login-brand"><span><HeartHandshake/></span><strong>An Tâm</strong></div><div><p className="login-kicker">AN TOÀN TẠI GIA</p><h1>An tâm hơn khi luôn có công nghệ đồng hành.</h1><p>Camera AI xử lý ngay trên thiết bị, giúp gia đình nhận biết tình huống bất thường mà vẫn giữ dữ liệu riêng tư trong ngôi nhà.</p><div className="login-trust"><ShieldCheck/><span><strong>Riêng tư từ thiết kế</strong><small>Video thô không được gửi lên cloud.</small></span></div></div></section><section className="login-form-panel"><form className="login-card" onSubmit={submit}><div className="login-mobile-brand"><HeartHandshake/><strong>An Tâm</strong></div><header><p>{user?.force_password_change?"BẢO MẬT TÀI KHOẢN":"CHÀO MỪNG TRỞ LẠI"}</p><h2>{user?.force_password_change?"Đổi mật khẩu":"Đăng nhập"}</h2><span>{user?.force_password_change?"Bạn cần đặt mật khẩu mới trước khi sử dụng hệ thống.":"Truy cập hệ thống giám sát an toàn gia đình."}</span></header>{error&&<div className="login-error" role="alert">{error}</div>}{!user?.force_password_change&&<label><span>Tên đăng nhập hoặc Email</span><div className="login-input"><UserRound/><input name="identity" autoComplete="username" required autoFocus placeholder="Nhập tên đăng nhập hoặc email"/></div></label>}<label><span>{user?.force_password_change?"Mật khẩu mới":"Mật khẩu"}</span><div className="login-input"><LockKeyhole/><input name="password" type={visible?"text":"password"} minLength={user?.force_password_change?8:1} autoComplete={user?.force_password_change?"new-password":"current-password"} required placeholder={user?.force_password_change?"Tối thiểu 8 ký tự":"Nhập mật khẩu"}/><button type="button" onClick={()=>setVisible(!visible)} aria-label={visible?"Ẩn mật khẩu":"Hiện mật khẩu"}>{visible?<EyeOff/>:<Eye/>}</button></div></label>{!user?.force_password_change&&<div className="login-options"><label><input name="remember" type="checkbox"/> Ghi nhớ đăng nhập</label><a href="mailto:admin@antam.local">Quên mật khẩu?</a></div>}<button className="login-submit" disabled={loading}>{loading?<i aria-label="Đang xử lý"/>:user?.force_password_change?"Lưu mật khẩu mới":"Đăng nhập"}</button>{!user?.force_password_change&&<p className="login-account-note">Tài khoản được cấp bởi quản trị viên gia đình. Liên hệ quản trị viên nếu bạn chưa có tài khoản.</p>}</form></section></main>
}
