import { useState } from "react";
import {
  Bell, Camera, Check, Clock3, KeyRound, Mail, Plus, Save, ShieldCheck,
  SlidersHorizontal, Smartphone, UserPlus, Video, X,
} from "lucide-react";

function InstantToggle({ value, onChange, disabled = false, label }: { value: boolean; onChange: () => void; disabled?: boolean; label: string }) {
  return <button className={`permission-toggle ${value ? "on" : ""}`} role="switch" aria-checked={value} aria-label={label} disabled={disabled} onClick={onChange}><i /></button>;
}

function SavedButton({ label = "Lưu thay đổi" }: { label?: string }) {
  const [saved, setSaved] = useState(false);
  return <button className={`settings-save ${saved ? "saved" : ""}`} onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 1400); }}>{saved ? <><Check /> Đã lưu</> : <><Save /> {label}</>}</button>;
}

const initialCameras = [
  { id: "c1", name: "Camera phòng khách", location: "Phòng khách", source: "webcam", status: "online", lastSeen: "Vừa xong", active: true },
  { id: "c2", name: "Camera phòng ngủ", location: "Phòng ngủ", source: "video_file", status: "offline", lastSeen: "12 phút trước", active: true },
  { id: "c3", name: "Camera hành lang", location: "Hành lang tầng 1", source: "video_file", status: "error", lastSeen: "2 giờ trước", active: false },
];
export function GeneralSettings() {
  const [cameras, setCameras] = useState(initialCameras);
  const [dialog, setDialog] = useState<"camera" | null>(null);
  const [encrypted, setEncrypted] = useState(true);
  const [strangerThreshold, setStrangerThreshold] = useState(78);
  const [fallThreshold, setFallThreshold] = useState(72);
  const [sensitive, setSensitive] = useState(true);
  return <div className="settings-scroll-content">
    <header className="section-page-heading"><div><h2>Cài đặt chung</h2><p>Cấu hình hồ sơ, thiết bị AI và các nguyên tắc an toàn.</p></div></header>
    <section className="settings-section-card"><div className="settings-card-heading"><span><KeyRound /></span><div><h3>Hồ sơ quản trị viên</h3><p>Thông tin dùng để quản trị hệ thống cục bộ.</p></div></div><div className="settings-form-grid"><label><span>Tên hiển thị</span><input defaultValue="Quản trị viên" /></label><label><span>Email</span><input type="email" defaultValue="admin@example.local" /></label><label><span>Mật khẩu mới</span><input type="password" placeholder="Để trống nếu không đổi" /></label></div><div className="settings-card-actions"><SavedButton /></div></section>
    <section className="settings-section-card"><div className="settings-card-heading row"><span><Camera /></span><div><h3>Quản lý camera</h3><p>{cameras.length} nguồn webcam/video đang được cấu hình.</p></div><button className="settings-primary-small" onClick={() => setDialog("camera")}><Plus /> Thêm camera</button></div><div className="settings-data-list">{cameras.map((item) => <div className="camera-setting-row" key={item.id}><span className="data-icon"><Video /></span><div><strong>{item.name}</strong><small>{item.location} · {item.source === "webcam" ? "Webcam" : "Video mô phỏng"}</small></div><span className={`operational-badge ${item.status}`}>{item.status === "online" ? "Trực tuyến" : item.status === "offline" ? "Ngoại tuyến" : "Lỗi"}</span><time>{item.lastSeen}</time><InstantToggle label={`Kích hoạt ${item.name}`} value={item.active} onChange={() => setCameras((rows) => rows.map((row) => row.id === item.id ? { ...row, active: !row.active } : row))} /></div>)}</div></section>
    <section className="settings-section-card"><div className="settings-card-heading"><span><ShieldCheck /></span><div><h3>Quyền riêng tư & bảo mật</h3><p>Các bảo vệ bắt buộc không thể bị tắt.</p></div></div><div className="privacy-guarantees"><p><Check /> Xử lý hoàn toàn on-device — không gửi video thô lên cloud</p><p><Check /> Khuôn mặt người lạ luôn được làm mờ tự động</p></div><div className="setting-inline-row"><label><span>Thời gian lưu snapshot</span><select defaultValue="30"><option value="7">7 ngày</option><option value="30">30 ngày</option><option value="90">90 ngày</option></select></label><div><strong>Mã hoá lưu trữ cục bộ</strong><small>Bảo vệ database và embedding trên laptop.</small></div><InstantToggle label="Mã hoá lưu trữ cục bộ" value={encrypted} onChange={() => setEncrypted((value) => !value)} /></div><div className="settings-card-actions"><SavedButton /></div></section>
    <section className="settings-section-card"><div className="settings-card-heading"><span><SlidersHorizontal /></span><div><h3>Ngưỡng cảnh báo & giảm báo động giả</h3><p>Điều chỉnh độ nhạy của cảnh báo AI.</p></div></div><div className="threshold-grid"><label><span>Phát hiện người lạ <strong>{strangerThreshold}%</strong></span><input type="range" min="50" max="99" value={strangerThreshold} onChange={(event) => setStrangerThreshold(Number(event.target.value))} /></label><label><span>Nghi ngờ té ngã <strong>{fallThreshold}%</strong></span><input type="range" min="70" max="99" value={fallThreshold} onChange={(event) => setFallThreshold(Number(event.target.value))} /><small>Không thể đặt dưới mức an toàn khuyến nghị — ưu tiên không bỏ sót té ngã.</small></label></div><div className="sensitive-hours"><Clock3 /><div><strong>Khung giờ nhạy cảm</strong><small>Tăng severity một bậc khi có người lạ ngoài giờ.</small></div><input type="time" defaultValue="22:00" /><span>đến</span><input type="time" defaultValue="06:00" /><select><option>Tất cả camera</option><option>Camera cửa chính</option></select><InstantToggle label="Bật khung giờ nhạy cảm" value={sensitive} onChange={() => setSensitive((value) => !value)} /></div><div className="settings-card-actions"><SavedButton /></div></section>
    {dialog && <div className="settings-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setDialog(null)}><form className="settings-modal" onSubmit={(event) => { event.preventDefault(); setDialog(null); }}><header><div><h3>Thêm camera</h3><p>Kết nối webcam hoặc video MP4 mô phỏng.</p></div><button type="button" onClick={() => setDialog(null)}><X /></button></header><label><span>Tên camera</span><input required placeholder="Camera sân trước" /></label><label><span>Vị trí</span><input required placeholder="Sân trước" /></label><label><span>Loại nguồn</span><select><option>Webcam</option><option>Video MP4</option></select></label><label><span>Đường dẫn nguồn tương đối</span><input placeholder="samples/camera-demo.mp4" /></label><footer><button type="button" onClick={() => setDialog(null)}>Huỷ</button><button type="submit">Thêm camera</button></footer></form></div>}
  </div>;
}

type DemoUser = { id: string; name: string; email: string; role: "admin" | "caregiver"; active: boolean; created: string };
export function UsersSettings() {
  const [users, setUsers] = useState<DemoUser[]>([
    { id: "u1", name: "Quản trị viên", email: "admin@example.local", role: "admin", active: true, created: "03/08/2026" },
    { id: "u2", name: "Minh Nguyễn", email: "caregiver@example.local", role: "caregiver", active: true, created: "03/08/2026" },
    { id: "u3", name: "Mai Anh", email: "maianh@example.local", role: "caregiver", active: true, created: "03/08/2026" },
    { id: "u4", name: "Thanh Hà", email: "thanhha@example.local", role: "caregiver", active: false, created: "03/08/2026" },
  ]);
  const [invite, setInvite] = useState(false);
  const toggleUser = (user: DemoUser) => { if (user.role === "admin" && users.filter((item) => item.role === "admin" && item.active).length === 1) return; setUsers((rows) => rows.map((row) => row.id === user.id ? { ...row, active: !row.active } : row)); };
  return <div className="settings-scroll-content"><header className="section-page-heading"><div><h2>Quản lý người dùng</h2><p>Thêm, chỉnh sửa và vô hiệu hoá tài khoản truy cập.</p></div><button className="settings-primary-small" onClick={() => setInvite(true)}><UserPlus /> Mời thành viên</button></header><section className="settings-section-card user-table-card"><div className="settings-user-table"><div className="user-table-head"><span>Thành viên</span><span>Vai trò</span><span>Trạng thái</span><span>Ngày tạo</span><span>Hành động</span></div>{users.map((user) => <div className="user-table-row" key={user.id}><div><span className="caregiver-avatar">{user.name.split(" ").map((part) => part[0]).slice(-2).join("")}</span><span><strong>{user.name}</strong><small>{user.email}</small></span></div><span className={`role-badge ${user.role}`}>{user.role === "admin" ? "Admin" : "Caregiver"}</span><span className={`account-badge ${user.active ? "active" : "inactive"}`}>{user.active ? "Hoạt động" : "Đã khóa"}</span><time>{user.created}</time><div><button title="Đặt lại mật khẩu"><KeyRound /></button><button title={user.active ? "Vô hiệu hoá" : "Kích hoạt"} onClick={() => toggleUser(user)}><ShieldCheck /></button></div></div>)}</div><p className="last-admin-note"><ShieldCheck /> Không thể vô hiệu hoá admin cuối cùng đang hoạt động.</p></section>{invite && <div className="settings-modal-backdrop"><form className="settings-modal" onSubmit={(event) => { event.preventDefault(); setInvite(false); }}><header><div><h3>Mời thành viên</h3><p>Tạo tài khoản mới trong hệ thống.</p></div><button type="button" onClick={() => setInvite(false)}><X /></button></header><label><span>Tên hiển thị</span><input required /></label><label><span>Email</span><input type="email" required /></label><label><span>Vai trò</span><select><option value="caregiver">Caregiver</option><option value="admin">Admin</option></select></label><footer><button type="button" onClick={() => setInvite(false)}>Huỷ</button><button type="submit">Gửi lời mời</button></footer></form></div>}</div>;
}

export function NotificationSettings() {
  const [channels, setChannels] = useState({ app: true, email: true, sms: false, grouped: true, quiet: true });
  const toggle = (key: keyof typeof channels) => setChannels((value) => ({ ...value, [key]: !value[key] }));
  return <div className="settings-scroll-content"><header className="section-page-heading"><div><h2>Thông báo</h2><p>Chọn cách caregiver nhận và nhóm các cảnh báo an toàn.</p></div></header><section className="settings-section-card"><div className="settings-card-heading"><span><Bell /></span><div><h3>Kênh nhận cảnh báo</h3><p>Critical luôn được ưu tiên gửi qua kênh đang khả dụng.</p></div></div><div className="notification-options">{[{ key: "app" as const, icon: Bell, label: "Trong ứng dụng", note: "Thông báo và badge trong An Tâm" }, { key: "email" as const, icon: Mail, label: "Email", note: "Gửi tới email tài khoản" }, { key: "sms" as const, icon: Smartphone, label: "SMS", note: "Chưa có hạ tầng — chế độ mô phỏng" }].map(({ key, icon: Icon, label, note }) => <div key={key}><Icon /><span><strong>{label}</strong><small>{note}</small></span><InstantToggle label={label} value={channels[key]} onChange={() => toggle(key)} disabled={key === "sms"} /></div>)}</div></section><section className="settings-section-card"><div className="settings-card-heading"><span><SlidersHorizontal /></span><div><h3>Mức độ & gộp thông báo</h3><p>Giảm nhiễu nhưng vẫn ưu tiên tình huống quan trọng.</p></div></div><div className="setting-inline-row"><label><span>Mức độ nhận thông báo</span><select defaultValue="all"><option value="all">Nhận tất cả</option><option value="important">Chỉ high / critical</option></select></label></div><div className="notification-toggle-row"><div><strong>Gộp cảnh báo liên tiếp</strong><small>Gộp các cảnh báo trong 5 phút thành một thông báo.</small></div><InstantToggle label="Gộp cảnh báo" value={channels.grouped} onChange={() => toggle("grouped")} /></div></section><section className="settings-section-card"><div className="settings-card-heading"><span><Clock3 /></span><div><h3>Giờ yên tĩnh</h3><p>Không gửi cảnh báo không khẩn cấp trong khoảng thời gian này.</p></div></div><div className="quiet-hours"><InstantToggle label="Bật giờ yên tĩnh" value={channels.quiet} onChange={() => toggle("quiet")} /><label><span>Từ</span><input type="time" defaultValue="22:00" disabled={!channels.quiet} /></label><label><span>Đến</span><input type="time" defaultValue="06:00" disabled={!channels.quiet} /></label><p><ShieldCheck /> Cảnh báo critical vẫn luôn được gửi.</p></div><div className="settings-card-actions"><SavedButton label="Lưu thông báo" /></div></section></div>;
}
